### ISSUE TITLE
add option download model via torrent/magnet

### ISSUE THREAD

**Issue by ShadeRedeye** [Miraculix200/StableDiffusionUI_SageMakerSL#1]
could you make that work ? there a model that can only be obtain by torrenting

**Comment by Miraculix200** [comment]
SageMaker Studio Lab seems very restrictive with network connections. It can't even establish gradio or localtunnel connections. Only ngrok works. So torrenting will not work either.

I've added some new models from https://huggingface.co/acheong08 to the notebook, maybe that profile has something you were searching for
