### ISSUE TITLE
is there a way to make images not save to tmp?

### ISSUE THREAD

**Issue by nagaisa** [Miraculix200/StableDiffusionUI_SageMakerSL#2]
i want to keep my images

**Comment by Miraculix200** [comment]
Yes, comment out this line:
`!ln -vs /tmp/outputs stable-diffusion-webui/outputs`
and change this line
`!mkdir -p /tmp/outputs`
to 
`!mkdir -p ~/sagemaker-studiolab-notebooks/stable-diffusion-webui/outputs`

**Comment by Miraculix200** [comment]
I forgot you may have to enter 
`rm ~/sagemaker-studiolab-notebooks/stable-diffusion-webui/outputs` 
in the console before starting the webui the next time
